# This CI will run after publish a new release

name: Push to Other Repo and Make a PR

on: 
  release:
    types: [published]

# on: 
#   push:
#       paths : 
#       - 'docs/*'
#       - 'readme.adoc'
#       branches :
#       - master
# triger with spesific path
  
jobs:
  processing_docs:
#     if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push then create PR
        uses: rnurdinb/push_then_pr@master
        env:
            API_TOKEN_GITHUB: ${{ secrets.API_INTEGRATED_REPO }}

            DEST_GITHUB_USERNAME: 'sepulsa'
            DEST_REPO_NAME: 'Ibis-Tummy'
            USER_EMAIL: 'test@example.com'
            PUSH_TO_BRANCH: 'docs-xpander'
            PR_TO_BRANCH: 'master'
            # You can add multiple source file or folder separate by space
            SRC_DIR: 'docs/*' 
            # You can create nested folder
            DEST_DIR: 'Testing-New-Stucture/Alterra-Bils/System-Documents/Xpander'
            # You can rename with format source(comma)target
            # Multiple line if you want to move multiple file / folder
#             RENAME: >-
#                     docs,Xpander
            # Add your custom Pull Request message
            PR_MESSAGE: 'New release from xpander' 
